defaults: &defaults
  parallel: 1
  resource_class: large
  working_directory: /root/current
  docker:
    - image: mavenlink/changestream-build:20170809c
    - image: mysql/mysql-server:5.7
      command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --log-bin=mysql-bin, --binlog_format=row, --binlog_rows_query_log_events, --server-id=952, --expire_logs_days=1]
      environment:
        MYSQL_ROOT_PASSWORD: "password"
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: "changestream_test"
  environment:
    MYSQL_HOST: "127.0.0.1"
    MYSQL_USER: "root"
    MYSQL_PASS: "password"
    SQS_QUEUE_NAME: "__circle-firehose"
    SNS_TOPIC_NAME: "__circle-firehose"
    SBT_OPTS: "-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled"

version: 2
executorType: docker
jobs:
  build:
    <<: *defaults
    docker:
      - image: mavenlink/changestream-build:20170809c
    steps:
      - restore_cache:
          key: changestream-source-v1-{{ .Branch }}-
      - checkout
      - save_cache:
          key: changestream-source-v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /root/current
      - restore_cache:
          key: changestream-cache-v1-{{ .Branch }}-
      - run:
          name: Compile
          command: |
            sbt compile test:compile it:compile exit
            rm -rf /root/current/.git
      - save_cache:
          key: changestream-cache-v1-{{ .Branch }}-{{ epoch }}
          paths:
            - "/root/.ivy2"
            - "/root/.sbt"
            - "/root/current/target/resolution-cache"
            - "/root/current/target/streams"
            - "/root/current/project/target/resolution-cache"
            - "/root/current/project/target/streams"
      - persist_to_workspace:
          root: /root
          paths:
            - current
            - ".ivy2"
            - ".sbt"

  unit-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: Unit Tests
          command: |
            sbt test
      - store_test_results:
          path: /root/current/target/test-reports

  integration-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: Integration Tests
          command: |
            sbt it:test
      - store_test_results:
          path: /root/current/target/test-reports

  integration-tests-gtid:
    <<: *defaults
    docker:
      - image: mavenlink/changestream-build:20170809c
      - image: mysql/mysql-server:5.7
        command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --log-bin=mysql-bin, --gtid_mode=on, --log-slave-updates, --enforce-gtid-consistency, --binlog_format=row, --binlog_rows_query_log_events, --server-id=952, --expire_logs_days=1]
        environment:
          MYSQL_ROOT_PASSWORD: "password"
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: "changestream_test"
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: Integration Tests
          command: |
            sbt it:test
      - store_test_results:
          path: /root/current/target/test-reports

  deploy:
    <<: *defaults
    docker:
      - image: mavenlink/changestream-build:20170809c
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: Build Debian Package
          command: |
            sbt debian:packageBin
            mkdir -p /tmp/circle/
            cp /root/current/target/*.deb /tmp/circle/
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command:  |
            sbt docker
            mkdir -p /tmp/circle/
            cp /root/current/target/docker/Dockerfile /tmp/circle/
      - deploy:
          name: Deploy to DockerHub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag mavenlink/changestream mavenlink/changestream:$CIRCLE_SHA1
            docker push mavenlink/changestream:$CIRCLE_SHA1
      - store_artifacts:
          path: /tmp/circle

  deploy_newrelic:
    <<: *defaults
    docker:
      - image: mavenlink/changestream-build:20170809c
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: Build Debian Package
          command: |
            sbt debian:packageBin
            mkdir -p /tmp/circle/
            cp /root/current/target/*.deb /tmp/circle/
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command:  |
            sbt docker
            mkdir -p /tmp/circle/
            cp /root/current/target/docker/Dockerfile /tmp/circle/
      - deploy:
          name: Deploy to DockerHub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag mavenlink/changestream mavenlink/changestream:newrelic-$CIRCLE_SHA1
            docker push mavenlink/changestream:newrelic-$CIRCLE_SHA1
      - store_artifacts:
          path: /tmp/circle

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
      - integration-tests:
          requires:
            - build
      - integration-tests-gtid:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - unit-tests
            - integration-tests
            - integration-tests-gtid
      - deploy_newrelic:
          filters:
            branches:
              only: newrelic
          requires:
            - unit-tests
            - integration-tests
            - integration-tests-gtid
